import { StyleSheet } from 'react-native';

export const uploadStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
    height: 56,
  },
  logoBadge: {
    backgroundColor: '#FF6F4D',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  logoText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  uploadArea: {
    width: '100%',
    alignItems: 'center',
  },
  uploadAreaButton: {
    width: 200,
    height: 200,
    borderWidth: 2,
    borderColor: '#FF6F4D',
    borderStyle: 'dashed',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  uploadAreaText: {
    color: '#FF6F4D',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 12,
  },
  uploadSubText: {
    color: '#666',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 8,
    paddingHorizontal: 20,
  },
  selectedVideoContainer: {
    width: '100%',
    alignItems: 'center',
  },
  videoPreview: {
    width: 200,
    height: 200,
    backgroundColor: '#f8f8f8',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#eee',
  },
  videoName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginTop: 12,
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  videoSize: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  changeVideoButton: {
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
  },
  changeVideoText: {
    color: '#333',
    fontSize: 16,
    fontWeight: '500',
  },
  bottomBar: {
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 32,
    height: 80,
    justifyContent: 'center',
  },
  uploadButton: {
    backgroundColor: '#FF6F4D',
    borderRadius: 8,
    paddingHorizontal: 40,
    paddingVertical: 12,
    minWidth: 120,
  },
  uploadButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  uploadButtonDisabled: {
    backgroundColor: '#ccc',
  },
  uploadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputContainer: {
    width: '100%',
    marginTop: 16,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    backgroundColor: '#fff',
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  inputHint: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
    fontStyle: 'italic',
  },
  infoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
  },
  infoText: {
    fontSize: 14,
    color: '#666',
    marginLeft: 8,
  },
}); 